# Generated by Django 4.1.7 on 2023-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlelab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessevent',
            name='teddy_response',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
